export const ZIP_CENTRAL_RECORD = {
  SIGNATURE: 0x06054b50,
  MIN_LENGTH: 22,
  CENTRAL_DIRECTORY_OFFSET: 10,
};

export const ZIP_CENTRAL_DIRECTORY = {
  MIN_LENGTH: 46,
  COMPRESSION_OFFSET: 10,
  NAME_LENGTH_OFFSET: 28,
  LOCAL_FILE_HEADER_OFFSET: 42,
  FILE_NAME_OFFSET: 46,
  COMPRESSED_SIZE_OFFSET: 20,
  UNCOMPRESSED_SIZE_OFFSET: 24,
};

export const ZIP_LOCAL_FILE_HEADER = {
  MIN_LENGTH: 30,
};
